### ISSUE TITLE
Great job Myles!

### ISSUE THREAD

**Issue by sonnynomnom** [Myles2/Cpp-Choose-your-path-project.#1]
Dear Myles,

Thank you for participating in the C++ Community Challenge 2019! This is a super super awesome project, and we had a lot of fun playing it. It's very unfortunate that your teammates didn't help. It was very sad to see `fabian()` and `marco()` with nothing in them :( But don't fret, we didn't take that into account!

**Criterion 1: Use of vectors and functions in your code**
Meets Expectations
Really liked the `cave()` and `cave_end()` functions! Very well written. But, I couldn't find any vectors! A cool way to incorporate vectors here is to create a vector of environment items (tree, wall, flower) and do an `std::cout` for a text string including a randomized item within the vector. A lot of games do this so the environment always feels "new". You could also create a vector of gameplay items such as heal potion, extra life, power up, etc and make the game a lot more complex.

**Criterion 2: Collaboration**
Not judged on this area. But we really appreciate the attempt to collaborate with your teammates and that's absolutely a plus in software dev.

**Criterion 3: Originality**
Exceeds Expectations
Incredible incredible idea. Love the writing. Very funny, super engaging. Loved the 3 keys storyline. It made us play it over and over again trying to find 1 key. Loved the castle ASCII art... I wish there are more! For example https://www.asciiart.eu/animals/bears 😀

**Criterion 4: Readability**
Exceeds Expectations
Some comments were added to clarify functionality (for example, you told your teammates exactly where to enter their code with 2 comments. Loved the ==== lines during output. Definitely felt like a movie and a lot of thought and care went into this. There was whitespace (both extra lines and indentation) to ease readability of the code.

**Further Room for Improvement:**
Mentioned above, it would be awesome if there is more randomness or more game complexity (items) involved. We also had some trouble in trying to figure out how to compile this program, mainly because **conio.h** is a Windows-specific file and we were on Macs (work computers). That definitely took us a while but no points deducted on that!

If you would like, you can submit your code this [repo](https://github.com/Codecademy/learn-cpp) so other learners can see it!

We'll reach out to each of you on slack with a link for a free t-shirt. If you don't hear from us, please slack **Sonny - Codecademy Staff** or **Mariel - Codecademy Staff**.

Happy coding,
Codecademy

**Comment by Myles2** [comment]
@sonnynomnom,

### Thank you so much, for taking out the time to give me feedback on my project!
I'm really glad you guys enjoyed it, that is very encouraging. Also, vectors for environments would be really awesome! I hope to implement a health system later on with battle rounds spread throughout the paths randomly. And **Definitely More ASCII Art!**

***Sorry about the <conio.h>*** I was trying to find a way to delay the script so it didn't go out of the frame so quickly but the solution to that online, only suggested system-specific ways and when I found <conio.h> it seemed as if it was for all systems but now that I know that, I've already implemented a way to change that in my next commit.

I hope to have a complete version by the end of this month, with as many special features as possible I'll make sure to send you guys a message when I finish. I would like to submit the code but I'm not exactly sure what you mean. Do you mean making a pull request or putting a link or something else entirely?

**Thanks for the T-shirt, you guys are Great!**
**Happy coding,**

**Myles**
